name: Build & Deploy Dataset to Hugging Face

on:
  push:
    branches:
      - main    # or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_REPO:  ${{ secrets.HF_REPO }}

    steps:
      - uses: actions/checkout@v4

    # 2) Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3) Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml huggingface_hub

    # 4) Build JSONL from YAML
    - name: Build JSONL
      run: python scripts/build_jsonl.py data_src data

    # 5) Clone the anonymized HF dataset repo
      - name: Clone HF dataset
        run: |
          git clone https://$HF_TOKEN@huggingface.co/$HF_REPO hf-data

      - name: Copy anonymous README
        run: |
          cp README_ANON.md hf-data/README.md

      - name: Sync JSONL
        run: |
          mkdir -p hf-data/data
          rm -f hf-data/data/*.jsonl
          cp data/*.jsonl hf-data/data/

      - name: Commit & Push to HF
        run: |
          cd hf-data
          git config user.name  "CI Bot"
          git config user.email "ci-bot@anonymous.invalid"
          git add README.md data/*.jsonl
          git commit -m "Auto-update dataset" || echo "Nothing to commit"
          git push https://$HF_TOKEN@huggingface.co/$HF_REPO.git HEAD:main
