name: Build & Deploy Dataset to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_REPO:  ${{ secrets.HF_REPO }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyyaml huggingface_hub
      - name: Build JSONL
        run: python scripts/build_jsonl.py data_src data
      - name: Clone HF dataset
        run: git clone https://huggingface.co/${HF_REPO} hf-data
      - name: Copy anonymous README
        run: cp README_ANON.md hf-data/README.md
      - name: Sync JSONL
        run: |
          mkdir -p hf-data/data
          rm -f hf-data/data/*.jsonl
          cp data/*.jsonl hf-data/data/
      - name: Commit & Push to HF
        run: |
          cd hf-data
          git config user.name  "CI Bot"
          git config user.email "ci-bot@anonymous.invalid"
          git add README.md data/*.jsonl
          git commit -m "Auto-update dataset" || echo "Nothing to commit"
          git -c http.extraheader="Authorization: Bearer $HF_TOKEN" \
              push https://huggingface.co/${HF_REPO}.git HEAD:main
